application: menrfa-hornbook-django
version: 2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: "1.5"

handlers:
- url: /_ah/queue/deferred
  script: libs.djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: libs.djangoappengine.appstats.application

- url: /media/admin
  static_dir: libs.django/contrib/admin/media
  expiration: '0'

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/img/favicon.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /api/index.html
  static_files: apps/hornbook_api/templates/hornbook_api/index.html
  upload: apps/hornbook_api/templates/hornbook_api/index.html

- url: /.*
  script: libs.djangoappengine.main.application
